spring:
  application:
    name: AIRBNB-BOOKINGSERVICE

  config:
    import: "optional:configserver:http://localhost:8888/"
  jpa:
    show-sql: true
    hibernate:

      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/airbnbdb
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8762/eureka/
server:
  port: 8082



