server:
  port: 9097

spring:
  application:
    name: AIRBNB-API-GATEWAY
  config:
    import: "optional:configserver:http://localhost:8888/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: lb://AIRBNB-BOOKINGSERVICE
          predicates:
            - Path=/bookings/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
